tap "beeftornado/rmtree"
tap "datawire/blackbird"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "itchyny/fillin"
tap "koekeishiya/formulae"
tap "rafi/tap"
tap "universal-ctags/universal-ctags"
cask "osxfuse"
brew "openssl"
brew "readline"
brew "python"
brew "ansible"
brew "aria2"
brew "aspell", args: ["with-lang-he", "without-lang-de", "without-lang-es", "without-lang-fr"]
brew "assh"
brew "atool"
brew "bash"
brew "bash-completion@2"
brew "bat"
brew "bc"
brew "calc"
brew "catimg"
brew "chafa"
brew "cloc"
brew "colordiff"
brew "coreutils"
brew "ctop"
brew "curl"
brew "go"
brew "dep"
brew "diff-so-fancy"
brew "docker-ls"
brew "editorconfig"
brew "entr"
brew "ethereum"
brew "exif"
brew "fd"
brew "figlet"
brew "findutils"
brew "fish"
brew "flake8"
brew "fortune"
brew "node"
brew "fx"
brew "fzf"
brew "fzy"
brew "gawk"
brew "gifsicle"
brew "git"
brew "git-cal"
brew "git-extras"
brew "git-quick-stats"
brew "glyr"
brew "gnutls"
brew "gnupg"
brew "gnu-sed"
brew "gopass"
brew "graphviz"
brew "grc"
brew "highlight"
brew "htop"
brew "httpie"
brew "python@2"
brew "httpstat"
brew "icdiff"
brew "id3lib"
brew "jq"
brew "jrnl"
brew "keychain"
brew "kubernetes-cli"
brew "kops"
brew "kubectx"
brew "kubernetes-helm"
brew "less"
brew "lf"
brew "lnav"
brew "mas"
brew "media-info"
brew "moreutils"
brew "mpc"
brew "ncdu"
brew "ncmpcpp"
brew "neofetch"
brew "neomutt"
brew "neovim", args: ["HEAD"]
brew "netcat"
brew "nmap"
brew "odt2txt"
brew "p7zip"
brew "trash"
brew "tree"
brew "pass"
brew "peco"
brew "pgcli"
brew "pidof"
brew "pinentry-mac"
brew "pinfo"
brew "pipenv"
brew "pngcrush"
brew "poppler"
brew "progress"
brew "proselint"
brew "pspg"
brew "pstree"
brew "pycodestyle"
brew "pyenv"
brew "rclone"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "rsync"
brew "shellcheck"
brew "siege"
brew "socat"
brew "sonobuoy"
brew "spark"
brew "sshfs"
brew "stern"
brew "subliminal"
brew "tarsnap"
brew "task"
brew "tcpdump"
brew "telnet"
brew "terminal-notifier"
brew "terraform"
brew "the_silver_searcher"
brew "tidy-html5"
brew "tig"
brew "tldr"
brew "tmux"
brew "tmux-mem-cpu-load"
brew "tmux-xpanes"
brew "ttyd"
brew "ttyrec"
brew "ttygif"
brew "unrar"
brew "urlview"
brew "vim"
brew "vit"
brew "watch"
brew "wego"
brew "wget"
brew "xmlstarlet"
brew "yamllint"
brew "yarn"
brew "z"
brew "zimg"
brew "zsh"
brew "itchyny/fillin/fillin", args: ["HEAD"]
brew "koekeishiya/formulae/chunkwm"
brew "rafi/tap/cam", args: ["HEAD"]
brew "rafi/tap/diana", args: ["HEAD"]
brew "rafi/tap/gits", args: ["HEAD"]
brew "rafi/tap/image2ascii", args: ["HEAD"]
brew "rafi/tap/imgcat"
brew "rafi/tap/lazygit", args: ["HEAD"]
brew "rafi/tap/reg"
brew "rafi/tap/timg", args: ["HEAD"]
brew "rafi/tap/tmuxp"
brew "rafi/tap/vint"
brew "rafi/tap/yaml2json"
brew "rafi/tap/yj", args: ["HEAD"]
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
cask "alacritty"
cask "android-studio"
cask "agenda"
cask "beyond-compare"
cask "clipy"
cask "contexts"
cask "dash"
cask "dozer"
cask "flux"
cask "handbrake"
cask "imageoptim"
cask "iterm2"
cask "karabiner-elements"
cask "keycastr"
cask "licecap"
cask "marked"
cask "minikube"
cask "mousepose"
cask "mpv"
cask "postman"
cask "skim"
cask "soulseek"
cask "spotify"
cask "qtpass"
cask "telegram-desktop"
cask "transmission"
cask "typora"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "visual-studio-code"
cask "whatsapp"
cask "xee"
mas "Bear", id: 1091189122
mas "iA Writer", id: 775737590
mas "Keynote", id: 409183694
mas "Microsoft Remote Desktop", id: 715768417
mas "MindNode", id: 1289197285
mas "Monosnap", id: 540348655
mas "Mousepose", id: 405904955
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator", id: 407963104
mas "Slack", id: 803453959
mas "Trello", id: 1278508951
mas "Xcode", id: 497799835
