tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "itchyny/fillin"
tap "koekeishiya/formulae"
tap "rafi/tap", "git@github.com:rafi/homebrew-tap.git"
tap "universal-ctags/universal-ctags"
brew "readline"
brew "python"
brew "ansible"
brew "aria2"
brew "aspell", args: ["with-lang-he", "without-lang-de", "without-lang-es", "without-lang-fr"]
brew "atool"
brew "bash"
brew "bash-completion@2"
brew "bat"
brew "bc"
brew "calc"
brew "catimg"
brew "ccat"
brew "cloc"
brew "colordiff"
brew "coreutils"
brew "ctop"
brew "curl"
brew "go"
brew "dep"
brew "diff-so-fancy"
brew "docker-ls"
brew "editorconfig"
brew "entr"
brew "ethereum"
brew "libexif"
brew "exif"
brew "exiv2"
brew "faad2"
brew "fd"
brew "figlet"
brew "findutils"
brew "fish"
brew "flake8"
brew "fortune"
brew "node"
brew "fx"
brew "fzf"
brew "fzy"
brew "gawk"
brew "gifsicle"
brew "git", args: ["with-curl", "with-openssl"]
brew "git-cal"
brew "git-extras"
brew "git-quick-stats"
brew "glyr"
brew "gnutls"
brew "gnupg"
brew "gnu-sed"
brew "gopass"
brew "graphviz"
brew "grc"
brew "highlight"
brew "htop"
brew "httpie"
brew "python@2"
brew "httpstat"
brew "icdiff"
brew "id3lib"
brew "jq"
brew "jrnl"
brew "keychain"
brew "kubernetes-cli"
brew "kubectx"
brew "kubernetes-helm"
brew "less"
brew "lf"
brew "libcaca", args: ["with-imlib2"]
brew "libgit2"
brew "libmms"
brew "libpq"
brew "lnav"
brew "mas"
brew "media-info"
brew "moreutils"
brew "mpc"
brew "zimg"
brew "mpv"
brew "ncdu"
brew "ncmpcpp"
brew "neofetch"
brew "neomutt"
brew "neovim", args: ["HEAD"]
brew "netcat"
brew "nmap"
brew "nnn"
brew "p7zip"
brew "pango"
brew "tree"
brew "pass"
brew "peco"
brew "pgcli"
brew "pidof"
brew "pinentry-mac"
brew "pipenv"
brew "pngcrush"
brew "poppler"
brew "progress"
brew "proselint"
brew "pspg"
brew "pstree"
brew "pycodestyle"
brew "ranger"
brew "rclone"
brew "reattach-to-user-namespace"
brew "resty"
brew "ripgrep"
brew "rsync"
brew "shellcheck"
brew "sonobuoy"
brew "spark"
brew "stern"
brew "subliminal"
brew "tarsnap"
brew "task"
brew "tcpdump"
brew "telnet"
brew "terminal-notifier"
brew "terraform"
brew "the_silver_searcher"
brew "tidy-html5"
brew "tig"
brew "tldr"
brew "tmux"
brew "tmux-mem-cpu-load"
brew "tmux-xpanes"
brew "ttyd"
brew "ttyrec"
brew "ttygif"
brew "unrar"
brew "upx"
brew "urlview"
brew "vim"
brew "vit"
brew "watch"
brew "wego"
brew "wget"
brew "wireguard-tools"
brew "xmlstarlet"
brew "yamllint"
brew "yarn"
brew "z"
brew "itchyny/fillin/fillin", args: ["HEAD"]
brew "koekeishiya/formulae/chunkwm"
brew "rafi/tap/cam", args: ["HEAD"]
brew "rafi/tap/diana", args: ["HEAD"]
brew "rafi/tap/gits", args: ["HEAD"]
brew "rafi/tap/image2ascii", args: ["HEAD"]
brew "rafi/tap/imgcat"
brew "rafi/tap/lazygit", args: ["HEAD"]
brew "rafi/tap/reg"
brew "rafi/tap/timg", args: ["HEAD"]
brew "rafi/tap/tmuxp"
brew "rafi/tap/vint"
brew "rafi/tap/yaml2json"
brew "rafi/tap/yj"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
cask "whatsapp"
mas "Bear", id: 1091189122
mas "ColorDial", id: 1064152481
mas "GarageBand", id: 408980954
mas "iA Writer", id: 775737590
mas "iMovie", id: 408981434
mas "iPhoto", id: 408981381
mas "MindNode", id: 1289197285
mas "Monosnap", id: 540348655
mas "Mousepose", id: 405904955
mas "Pixelmator", id: 407963104
mas "Slack", id: 803453959
mas "Trello", id: 1278508951
mas "Xcode", id: 497799835
