tap "apenngrace/vulkan"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "k1low/tap"
tap "khanhas/tap"
tap "koekeishiya/formulae"
tap "rafi/tap", "git@github.com:rafi/homebrew-tap.git"
tap "rigellute/tap"
tap "universal-ctags/universal-ctags"
brew "readline"
brew "ansible-lint"
brew "ansifilter"
brew "aria2"
brew "assh"
brew "atool"
brew "aws-iam-authenticator"
brew "awscli"
brew "bandwhich"
brew "bash"
brew "bash-completion@2"
brew "bat"
brew "bc"
brew "bingrep"
# brew "bitlbee"
brew "broot"
brew "calc"
brew "cassowary"
brew "catimg"
brew "x265"
brew "imagemagick"
brew "chafa"
brew "cloc"
brew "colordiff"
brew "coreutils"
brew "croc"
brew "openldap"
brew "curl"
brew "diff-so-fancy"
brew "dive"
brew "doctl"
brew "drone-cli"
brew "dust"
brew "editorconfig"
brew "empty"
brew "node"
brew "entr"
brew "exa"
brew "exif"
brew "exiv2"
brew "fd"
brew "fetch"
brew "gnutls"
brew "ffmpeg"
brew "figlet"
brew "findutils"
brew "fish"
brew "fortune"
brew "fx"
brew "fzf"
brew "fzy"
brew "gawk"
brew "gh"
brew "gifsicle"
brew "git"
brew "git-cal"
brew "git-delta"
brew "git-extras"
brew "git-filter-repo"
brew "git-quick-stats"
brew "gitui"
brew "glow"
brew "glyr"
brew "gnupg"
brew "gmime"
brew "gnu-sed"
brew "gnu-tar"
brew "go"
brew "gocloc"
brew "golangci-lint"
brew "googler"
brew "terminal-notifier"
brew "gopass"
brew "gopls"
brew "pango"
brew "graphviz"
brew "grc"
brew "grep"
brew "grv"
brew "heksa"
brew "helm"
brew "helm@2"
brew "help2man"
brew "hexyl"
# brew "hey"
brew "htop"
brew "httpie"
brew "httpstat"
brew "icdiff"
brew "id3lib"
brew "iftop"
# brew "interactive-rebase-tool"
brew "ioping"
brew "jid"
brew "jq"
brew "jrnl"
brew "json-c"
brew "jsonlint"
# brew "just"
brew "k3d"
# brew "kakoune"
brew "keychain"
brew "kind"
brew "kubernetes-cli"
brew "krew"
brew "kubectx"
brew "languagetool"
brew "lazygit"
brew "less"
brew "lf"
brew "litecli"
brew "lunchy-go"
brew "markdown-tui"
brew "mas"
brew "mdbook"
brew "media-info"
brew "minikube"
brew "mkcert"
brew "mkvalidator"
brew "mkvtoolnix"
brew "moreutils"
brew "mpc"
brew "n"
brew "ncdu"
brew "ncmpcpp"
brew "neofetch"
brew "neomutt"
brew "neovim", args: ["HEAD"]
brew "netcat"
brew "nextword"
brew "ngrep"
brew "nmap"
brew "nnn"
brew "noti"
brew "operator-sdk"
brew "p7zip"
brew "pandoc"
brew "tree"
brew "pass"
# brew "pastel"
brew "pg-flame"
brew "pgcli"
brew "pidof"
brew "pinentry-mac"
brew "pinfo"
brew "pipgrip"
brew "pngcrush"
brew "poetry"
brew "poppler"
brew "procs"
brew "proselint"
brew "pspg"
brew "pstree"
brew "pyenv"
brew "pyenv-virtualenv"
brew "rclone"
brew "reattach-to-user-namespace"
brew "ripgrep-all"
brew "robo"
brew "xxhash"
brew "rsync"
# brew "run"
brew "rustup-init"
# brew "sd"
brew "seq2gif"
brew "shellcheck"
brew "shfmt"
brew "siege"
brew "silicon"
brew "socat"
brew "sshpass"
brew "starship"
brew "stern"
brew "subfinder"
brew "subliminal"
brew "subnetcalc"
brew "sup"
brew "syncthing", restart_service: true
brew "task"
brew "tcpdump"
brew "telnet"
brew "terraform"
brew "tflint"
brew "the_silver_searcher"
brew "tidy-html5"
brew "tig"
brew "tmux"
brew "tmux-mem-cpu-load"
brew "tmux-xpanes"
# brew "topgrade"
brew "trash-cli"
brew "tty-share"
brew "ttyd"
brew "ttyrec"
brew "ttygif"
# brew "twtxt"
brew "ugrep"
brew "unrar"
brew "unzip"
# brew "upx"
brew "urlview"
brew "vercel-cli"
brew "vim", args: ["HEAD"]
brew "vit"
brew "vivid"
brew "w3m"
# brew "volt"
brew "watch"
brew "weechat"
brew "wget"
# brew "wordnet"
brew "write-good"
# brew "xmlrpc-c"
brew "xmlstarlet"
brew "yaml2json"
brew "yamllint"
brew "yank"
brew "yarn"
brew "yj"
brew "youtube-dl"
brew "yq"
brew "zlua", args: ["HEAD"]
brew "zoxide"
brew "zplug"
brew "zsh"
brew "k1low/tap/colr"
brew "k1low/tap/lrep"
brew "k1low/tap/tbls"
brew "khanhas/tap/spicetify-cli"
brew "koekeishiya/formulae/skhd", args: ["HEAD"]
brew "koekeishiya/formulae/yabai", args: ["HEAD"]
brew "rafi/tap/browserpass"
brew "rafi/tap/complete-alias", args: ["HEAD"]
brew "rafi/tap/fz", args: ["HEAD"]
brew "rafi/tap/git-fame"
brew "rafi/tap/gits"
brew "rafi/tap/image2ascii"
# brew "rafi/tap/nextword"
brew "rafi/tap/lstags"
brew "rafi/tap/reg"
brew "rafi/tap/tmuxp"
brew "rafi/tap/vint"
brew "rafi/tap/workon-py", args: ["HEAD"]
brew "rigellute/tap/spotify-tui"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD", "with-jansson", "with-libyaml"]
# cask "anki"
cask "beyond-compare"
# cask "bob"
cask "brave-browser"
cask "clipy"
cask "cloudapp"
cask "contexts"
cask "deckset"
cask "docker"
cask "dozer"
cask "drawio"
cask "firefox"
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-fontawesome"
cask "font-gohufont-nerd-font"
cask "font-hasklug-nerd-font"
cask "font-im-writing-nerd-font"
cask "font-iosevka"
cask "font-iosevka-nerd-font"
cask "font-jetbrains-mono"
cask "font-victor-mono-nerd-font"
cask "fsnotes"
cask "google-chat"
cask "google-cloud-sdk"
cask "gridea"
cask "handbrake"
cask "hyperdock"
cask "iina"
cask "imageoptim"
cask "inkscape"
cask "iterm2"
cask "joplin"
cask "karabiner-elements"
cask "keycastr"
cask "kitty"
cask "launchcontrol"
cask "licecap"
cask "mactex"
cask "marked"
cask "meetingbar"
cask "mousepose"
cask "mpv"
cask "netnewswire"
cask "nfov"
cask "ngrok"
cask "obsidian"
cask "paw"
cask "pixel-picker"
cask "plex-media-server"
cask "postman"
# cask "signal"
cask "skim"
cask "slack"
# cask "soulseek"
cask "spotify"
cask "tableplus"
cask "telegram"
cask "transmission"
cask "transmit"
cask "typora"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "visual-studio-code"
cask "vnote"
cask "vulkan-sdk"
cask "whatsapp"
cask "wireshark"
cask "yu-writer"
cask "zerotier-one"
cask "zoom"
cask "zoomus"
mas "Bear", id: 1091189122
mas "ColorSlurp", id: 1287239339
mas "GarageBand", id: 682658836
mas "iA Writer", id: 775737590
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Monosnap", id: 540348655
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator", id: 407963104
# mas "PopClip", id: 445189367
mas "Trello", id: 1278508951
