#!/usr/bin/env bash

bspc config top_padding       -23
bspc config split_ratio      0.52
bspc config border_width        2
bspc config window_gap         10

bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config normal_border_color   "#5E7175"
bspc config focused_border_color  "#536B3D"

xsetroot -cursor_name left_ptr

# Adopt ophan windows
bspc control --adopt-orphans

bspc rule -a mpv floating=on
bspc rule -a Gimp follow=on floating=on
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Always float chrome chat windows
bspc rule -a crx_nckgahadagoaajjgafhacjanaoiihapd floating=on

# Load urxvt-client and tmux on startup
/opt/local/bin/urxvtc -cd "$HOME" -e /opt/local/bin/tmux -f "$HOME/.config/tmux/config"
