#!/usr/bin/env bash

# rga (ripgrep-all) + fzf-tmux
# find-in-file - usage: fif <searchTerm> or fif "string with spaces" or fif "regex"
fif() {
	if [ ! "$#" -gt 0 ]; then echo "Need a string to search for!"; return 1; fi
	local file
	file="$(rga --max-count=1 --ignore-case --files-with-matches --no-messages "$@" | fzf-tmux +m --preview="rga --ignore-case --pretty --context 10 '"$@"' {}")" && open "$file"
}

#  vim: set ts=2 sw=2 tw=80 noet :
