#!/usr/bin/env bash

# Spellcheck with aspell
spell() {
  echo "$@" | aspell -a | egrep -v "^@|^$"
}

# Show active aria2 downloads with diana
da() {
  watch -ctn 3 "(echo '\033[32mGID\t\t Name\t\t\t\t\t\t\t%\tDown\tSize\tSpeed\tUp\tS/L\tTime\033[36m'; \
    diana list| cut -c -112; echo '\033[37m'; diana stats)"
}
