#!/usr/bin/env bash

# Quickly grep a process
function psg() {
	ps auxww | grep -i --color=always "$@" | grep -v "grep.*$@"
}

# Select command name with fzf and show memory usage
function psmem() {
	ps -o rss= -p $(pidof "$(ps -ec | fzf | awk '{print $4}')") \
		| awk '{print $1*4, "KiB"}'
}

function mtop() {
	ps -ceo pmem,pid,pcpu,rss,vsz,time,command | sort -k 1 -r | head -15 \
		| awk '
				function human(x) {
					if (x < 1000) { return x }
					x /= 1024;
					s = "MGTEPYZ";
					while (x >= 1000 && length(s) > 1) {
						x /= 1024;
						s = substr(s, 2)
					}
					return int(x + 0.5) substr(s, 1, 1)
				}
				{
					if (NR > 1) {
						sub($4, human($4));
						sub($5, human($5));
					}
					print
				}'
}
