#      .-.     .-.     .-.     .-.     .-.     .-.
# `._.'   `._.'   `._.'   `._.'   `._.'   `._.'   `
#
# github.com/rafi ~/.bashrc config

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# https://wiki.archlinux.org/index.php/RTorrent
# Ctrl-s is often used for terminal control to stop screen output while Ctrl-q is used to
# start it. These mappings may interfere with rTorrent. Check to see if these terminal
# options are bound to a mapping:
#   $ stty -a
# Remove the ^S ^Q mappings
stty stop undef
stty start undef

# Bash options
shopt -s cdspell        # autocorrects cd misspellings
shopt -s checkwinsize   # update the value of LINES and COLUMNS after each command if altered
shopt -s cmdhist        # save multi-line commands in history as single line
shopt -s dotglob        # include dotfiles in pathname expansion
shopt -s expand_aliases # expand aliases
shopt -s extglob        # enable extended pattern-matching features
shopt -s histreedit     # Add failed commands to the bash history
shopt -s histappend     # Append each session's history to $HISTFILE
shopt -s autocd         # Autocd

export HISTSIZE=2000
export HISTFILESIZE=50000
export HISTFILE="$XDG_CACHE_HOME/bash_history"
export HISTCONTROL=ignoreboth
export VISUAL=vim
export EDITOR="$VISUAL"
export PAGER=less

# Source aliases
source "$XDG_CONFIG_HOME/bash/aliases"

# Source bash completions
source "$XDG_CONFIG_HOME/bash/completion"

# Set the window title to user@host:dir
case "$TERM" in
xterm*|rxvt*|screen*)
	# Show a "user@host: /dir" in terminal title
	PROMPT_COMMAND='history -a; echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD}\007"'
	;;
*)
	;;
esac

# Load CLI utilities
source "$XDG_CONFIG_HOME/bash/utils"

# Load symlinked command prompt theme
source "$XDG_CONFIG_HOME/bash/themes/current"

# Load directory and file colors for GNU ls
eval $(dircolors -b "$XDG_CONFIG_HOME/bash/dircolors")

# vim: set ts=2 sw=2 tw=80 noet :
