#!/bin/bash
#      .-.     .-.     .-.     .-.     .-.     .-.     .-.     .-.     .-.
# `._.'   `._.'   `._.'   `._.'   `._.'   `._.'   `._.'   `._.'   `._.'   `._.'
#
# github.com/rafi ~/.profile

source "$HOME/.config/bash/exports"
source "$HOME/.bashrc"

# Use keychain to load keys
# https://github.com/funtoo/keychain
eval `keychain --dir "$XDG_CACHE_HOME/keychain" --eval --agents ssh -Q --quiet id_rsa rafi_sortex_rsa`

#if [ -n "$IS_SSH" ]; then
#	hash tmux 2>/dev/null && tmux has 2>/dev/null && exec tmux attach
#fi
