#!/usr/bin/env bash

# Theme: Haskell
# --------------
# basename/ λ: ▏
#
# Within Git repository:
# basename/branch λ: ▏
#
# Within SSH session:
# hostname:basename/branch λ: ▏
#
# Within virtualenv:
# venv/basename/branch λ: ▏

function ps1_context {
	local virtualenv
	if [ -n "$VIRTUAL_ENV" ]; then
		virtualenv="$(basename "$VIRTUAL_ENV")"
		echo -n "${virtualenv:+${virtualenv}/}"
	fi
}

if [ -z "$SSH_CLIENT" ] && [ -z "$SSH_TTY" ]; then
	# Local connections
	PS1='\[\e[0;31m\]$(ps1_context)\[\e[0;34m\]${PWD##*/}/\[\e[1;90m\]$(__git_ps1 "%s") \[\e[0;32m\]λ\[\e[00m\]: '
else
	# Remote connections
	PS1='\[\e[0;31m\]$(ps1_context)\[\e[0;33m\]\h\[\e[1;90m\]:\[\e[0;34m\]${PWD##*/}/\[\e[1;90m\]$(__git_ps1 "%s") \[\e[0;32m\]λ\[\e[00m\]: '
fi
