#!/usr/bin/env bash

# Theme: Haskell
# --------------
# basename/ λ: █
#
# Within Git repository:
# basename/branch λ: █
#
# Within SSH session:
# hostname:basename/branch λ: █
#
# IS_SSH is exported in bash/exports
if [ -z "$IS_SSH" ]; then

	# Local connections
	PS1='\[\e[0;34m\]${PWD##*/}/\[\e[1;30m\]$(__git_ps1 "%s") \[\e[0;32m\]λ\[\e[00m\]: '
else
	# Remote connections
	PS1='\[\e[0;33m\]\h\[\e[1;30m\]:\[\e[0;34m\]${PWD##*/}/\[\e[1;30m\]$(__git_ps1 "%s") \[\e[0;32m\]λ\[\e[00m\]: '
fi
